### ISSUE TITLE
(import-macros ...) compatibility with conjure

### ISSUE THREAD

**Issue by rktjmp** [rktjmp/hotpot.nvim#1]
We autocompile fnl files as requested, meaning you can `(require :my.fnl.mod)` in your conjure session without having to do anything, but `(import-macros ...)` fails for some reason with module not found. The stacktrace doesn't include hotpot so maybe conjure hijacks those calls specifically.

It did look like it was hitting require with utils.path, would have thought it would work.

Tried various cwd's and package.path should be fine, no access to fennel.path if it's using that.

**Comment by Olical** [comment]
For the record, I hope to get rid of the need for the module macros at some point but that requires making Aniseed's evals "stateful", so every buffer you enter a Fennel REPL is started to give you contextual evals within the context of a buffer.

I also kinda wanted to rewrite the module macros in terms of a Fennel compiler plugin but that API isn't fully stable yet and was proving kinda tricky / not worth it.

So I think I'll begin to move towards smarter Clojure/Aniseed evals where each eval doesn't occur within a clean room, but a shared REPL state per-buffer. Then the module macros become entirely optional and could maybe be phased out / changed into something a lot lighter.

AMA through whatever means you want if you wanna collab on some of these ideas or just have questions you think I might know the answer to 😄 and feel free to hop into the Conjure discord if you aren't already, it's a fairly active Fennel discussion zone.

**Comment by Olical** [comment]
Heads up that Aniseed's eval system got an overhaul and I rewrote the module macro system: https://github.com/Olical/aniseed/issues/63

So now you can eval non-module macro things and state is maintained between evals in a buffer local REPL context. All Lua output from the module macros was massively shrunk and optimised. Might not help you but still, thought I'd make you aware!

This is only on the develop branch of Aniseed and Conjure while I finish off a few things mentioned in that issue and smoke test it for a few days.

**Comment by datwaft** [comment]
I tested this in the latest version, and it seems to work properly.

😀

**Comment by rktjmp** [comment]
Great, thanks for checking.
