### ISSUE TITLE
[Feature Request] Use float window to preview the lua code generated by `show_code`

### ISSUE THREAD

**Issue by 6cdh** [rktjmp/hotpot.nvim#10]
As the title, It would be better to preview the lua code generated by Fennel in float window rather than printing in command-line. If so, syntax highlight powered by treesitter can also work.

**Comment by shadmansaleh** [comment]
+1 for this

I was just about to open an issue .
Though I'd prefer opening in a split instead of float So I can keep an eye on that while editing .

**Comment by 6cdh** [comment]
I forgot it. Split window is definitely better with side by side view.

**Comment by rktjmp** [comment]
> Though I'd prefer opening in a split instead of float So I can keep an eye on that while editing.

That's actually why I had planned to *not* show a preview (the printed stuff was a stopgap just for me really).

My reason against it is it quickly becomes:

- I want a split bottom
- I want a split right
- Well I want a float
- I don't want to focus the float
- can we get a keybind to refresh the split?
- it shouldn't open a new float, it should replace the last
-  ...... :godmode:

Basically it adds a whole lot of window management, window config, blah blah, to Hotpot which I don't think belongs.

Hotpot will provide you a method to compile a file, selection or buffer (to file or string) or get the path to a file or module (#2), and it will probably be up to the user to show that somehow (the code to open a window/split and dump lines is pretty short, and the user can write that however they want).

I hope to keep Hotpot about compiling and evaluating Fennel; and a bit of cache management and that's it.

(Probably I will make a hotpot side plugin that *does* do all the preview stuff, likely a bit like Lush with live preview, etc. It's just not likely to be part of *Hotpot.nvim*).

This isn't a hard no, but it's a "I don't really want to".

**Comment by shadmansaleh** [comment]
Ok I agree . I think what I think what will be a good compromise is you allow a function as argument to `show_selection()` & `show_buf` And feed the result to that function instead of print when available . That way we can do the window handling ourselves . What do you think of that ?

**Comment by 6cdh** [comment]
OK. I just tried conjure. It's so cool. I think we can integrate with it so that without focus on interaction. I would like to know how this plugin works with Conjure?

**Comment by rktjmp** [comment]
> Ok I agree . I think a good compromise if you add a callback to show_selection() & show_buf And feed the result to that function instead of print when available . That way we can do the window handling ourselves . What do you think of that ?

Yeah that's a nice way to do it, but `show_*` will probably be removed in favour of `compile_*` which returns a string, and the user can place that somewhere. I don't think it's practically different for the end user in the end? Not sure. Having a cb passed in does tickle my programmer brain in a good way though :snail:.

> OK. I just tried conjure. It's so cool. I think we can integrate with it so that without focus on interaction. I would like to know how this plugin works with Conjure?

Yes I use it with conjure. You can see why I am not so interested in rebuilding something like that when it's so stellar. There is an issue around `import-macros` (#1), do to with how aniseed works, seems like Olical is planning to rework conjure a bit to make it compat (I haven't deep dived into it but AFAIK it is a conjure qurik not a Hotpot one).

**Comment by shadmansaleh** [comment]
> I don't think it's practically different for the end user in the end? Not sure.

They are same for the user .

When I was looking at #2 I thought compile_file will write directly to output file .

**Comment by rktjmp** [comment]
Yeah there will be both probably, just thinking about it this very moment.

Right now there's all these https://github.com/rktjmp/hotpot.nvim/blob/shuffle/fnl/hotpot/user/compile.fnl which return strings.

```clojure 
{: compile-string
 : compile-range
 : compile-selection
 : compile-buffer
 : compile-file
 : compile-module}
```

Probably there will be a `/user/build.fnl` which will have `compile-file in out` and `compile-dir in out`.

I know it's a bit weird to have two functions named the same, but I don't really want to bleed "saving" into the compile module.

**Comment by rktjmp** [comment]
Going to close this as discussed, rendering output is beyond hotpots purview.

The new API is mainlined, with some examples on how to replace `show_code` in the Readme https://github.com/rktjmp/hotpot.nvim#using-the-api. It's reasonably trivial to wire up a float or split or whatever you would like.

And conjure.fun can provide nearly anything someone might want in terms of eval output.
