### ISSUE TITLE
`vim.loader` support

### ISSUE THREAD

**Issue by bb010g** [rktjmp/hotpot.nvim#101]
Hotpot should support & use [`vim.loader`](https://neovim.io/doc/user/lua.html#lua-loader) (implemented in <https://github.com/neovim/neovim/pull/22668>, released in [Neovim v0.9.0](https://neovim.io/doc/user/news-0.9.html#_-new-features)) for caching as much as possible, instead of implementing its own bytecode cache for Lua code (<https://github.com/rktjmp/hotpot.nvim/blob/9fd5d6e341861c776ec9c69a2fc524deae67b541/fnl/hotpot/index.fnl>).

**Comment by rktjmp** [comment]
Sorry, forgot to comment.

I _would_ like to use this, and drop our own cache.

Currently the loader is marked as experimental and disabled by default, so I don't think we are quite ready to swap. We also don't put any lua output in the traditional RTP, so as is, `vim.loader` would not function out of the box.

One way, maybe:

- Add a "hotpot lua root" to the very tail of the RTP
  - This retains the current behaviour of hotpot favouring `plugin.nvim/lua/x.lua` if it exists, over `plugin.nvim/fnl/x.lua` but the regular loader infra (including nvims cache) would eventually find the source file).
- Add hotpot loader to loader head
  - Perform search as we currently do, looking for `fnl/...` files, we can compute the lua source path
  - Run `vim.loader.find(:modname, {:rtp false :paths [lua_source_path]})`
    - Use the stat values from this against our fnl path stats and decide whether to recompile fnl -> lua.
    - If the stat values are out of date, we theoretically should just be able to dump the new lua source out, then have our loader "fail" to find anything, which will cause lua to continue on to `vim.loader`, which should take over finding the lua source (in the "hotpot lua root") and put that in cache, or find the module in-cache already and do its own invalidation check.

I have been also considering whether future versions of Hotpot will dump to the traditional `lua` dir or not, less moving parts but a bit uglier IMO.
