### ISSUE TITLE
Broken on Windows because `vim.fs.normalize` converts all path separators to forward slash (`\` -> `/`)

### ISSUE THREAD

**Issue by s-cerevisiae** [rktjmp/hotpot.nvim#109]
Recent versions are using `vim.fs.normalize` to normalize paths but this replaces all "windows-style" backward slashes to forward ones, which is inconsistent with `path-sep`, causing `make-path` and probably more functions to break on Windows.

I set `path-sep` to `/` and everything seems to be working correctly now.

For a proper fix I suggest that you should ensure that all paths are normalized, then use `/` as the path separator for all platforms.

**Comment by rktjmp** [comment]
Bummer, sorry about the sharp edges. Thanks for looking into it. Sounds like I can dump all the path-sep code for `fs.normalize` which is great.

**Comment by rktjmp** [comment]
Are you able to test the `api-make-remake` branch?

**Comment by rktjmp** [comment]
Should be fixed in 0.9.0

**Comment by s-cerevisiae** [comment]
I think it works for me. Thank you!
