### ISSUE TITLE
Macro path configuration

### ISSUE THREAD

**Issue by homedirectory** [rktjmp/hotpot.nvim#136]
I am facing difficulties making Hotpot recognise my macro modules.

Consider the following directory structure:

```
project/
  fnl/
    stuff/
      macros.fnl
      init.fnl
```

Also assume that `init.fnl` contains `(import-macros {...} "stuff.macros")`.

Then, if the current working directory (CWD henceforth) is `project` and I'm compiling
`fnl/stuff/init.fnl` (by writing to it), Hotpot fails to find the macro module:

```
Compile error: stuff.macros module not found.
```

However, if the CWD is `project/fnl/`, the macro module is found and compilation of `stuff/init.fnl` succeeds.

I guess the underlying reason is that `fennel.macro-path`, which is used to look up macro modules,
is set to `./?.fnl;./?/init-macros.fnl;./?/init.fnl;$FENNEL_MACRO_PATH` by default, which won't
match anything inside `fnl/`.

I haven't found any mention of macro path configuration in the documentation of Hotpot, so I tried
the following approach:

```lua
-- .hotpot.lua
local fennel = require("fennel")
fennel["macro-path"] = fennel["macro-path"] .. ";./fnl/?.fnl"
```

With this I have observed some strange behaviour.
Compilation of any file fails with:

```
src/fennel/macros.fnl:104:48 Compile error: unknown identifier: fennel-module-name

          traceback `(. (or (. package.loaded ,(^[[7mfennel-module-name^[[0m)) debug)
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.fennel-module-name if you really want a global.
* Try moving this code to somewhere that fennel-module-name is in scope.
* Try binding fennel-module-name as a local in the scope of this code.
```

All further attempts at compilation fail with:

```
Error executing lua callback: ...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:179: attempt to index local 'fennel' (a number value)
stack traceback:
	...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:179: in function 'do_compile'
	...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:320: in function 'build'
	...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:580: in function '_159_'
	...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:710: in function <...te/pack/packer/start/hotpot.nvim/lua/hotpot/api/make.lua:685>
```

However, if I perform the very first compilation with the above lines in `.hotpot.lua` commented
out, and then uncomment them -- all subsequent compilations succeed, and the new macro path is
recognised.

So right now I have 2 solutions:
1. Set the CWD to `fnl/`.
2. Perform the ritual with the very first compilation as described above.

It would be great if the macro path could be configured with Hotpot.

**Comment by rktjmp** [comment]
I guess `project` is not in neovims RTP? eg its not a "plugin", but instead you're using hotpot as a fennel build system for another thing? You can symlink it into the rtp which would let the regular searchers work,

```bash
$ mkdir -p ~/.local/share/nvim/site/pack/custom/start # custom can be anything
$ ln -s ~/some/path/project ~/.local/share/nvim/site/pack/custom/start/project
```

The problem with altering the search path is it effects all fennel actions afterwards since its modifying the global state. I have wanted to isolate each compiler in its own thread and lua-state which would make this better.

The error your seeing is actually from fennel's own compiler, I'm not sure why its not setting the module name internally.

I know I previously thought about just adding `fnl/` to the default searcher paths on load but did not want to stray too far from the fennel defaults and decided not to.

**Comment by homedirectory** [comment]
`project` is indeed not in the RTP, although it is in fact a NeoVim plugin I'm developing, I just haven't installed it yet.

> The problem with altering the search path is it effects all fennel actions afterwards since its modifying the global state.

What undesirable effects might this produce? Could my macro modules "leak" into the compiler?

**Comment by rktjmp** [comment]
> What undesirable effects might this produce? Could my macro modules "leak" into the compiler?

For you, not much in practice, but architecturally the setting will bleed between different `.hotpot.lua` instances/dirs (and the "default" compiler setup), so I would want a more "clean" way support it.

Reproducing what you described, I dont get an error and `lua/` is produced successfully. See attached zip.

[project.zip](https://github.com/rktjmp/hotpot.nvim/files/14893022/project.zip)

**Comment by homedirectory** [comment]
It's odd that you couldn't reproduce this issue. Did you try both cases: with CWD set to `project/` and to `project/fnl/`?

I just tried to reproduce this with plain Fennel via `fennel --compile fnl/stuff/init.fnl` (CWD is `project/`) and I did get the error.

Also here are some additional details that might help understand this discrepancy:
* NeoVim `v0.9.5` with Lua version `5.1`
* Fennel version: `1.4.0` (By the way, does Hotpot use its own Fennel compiler, effectively ignoring the installed one?)

**Comment by rktjmp** [comment]
Hotpot does ship its own copy of Fennel, so you do not need any system packages or additional lua packages installed. The version in Hotpot is unmodified from upstream apart from one added compiler callback (https://github.com/rktjmp/hotpot.nvim/commit/18008d48be6caeedad6f24876fbb5b5ebbe19ff7), to end users its identical.

You must enable the `provide_require_fennel` setup option as described in the readme for `require("fennel")` to work (this is to be friendly to other packages that may include their own fennel versions -- but likely I will flip the default to true in the next release). 

The following Containerfile shows it functioning as expected:

```containerfile
FROM archlinux/archlinux:latest
RUN <<EOF
pacman -Syu --noconfirm git neovim wget unzip tree
cd /root/
wget https://github.com/rktjmp/hotpot.nvim/files/14893022/project.zip
unzip project.zip
mkdir -p /root/.config/nvim
EOF
RUN cat <<EOF > /root/.config/nvim/init.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.notify("Bootstrapping lazy.nvim...", vim.log.levels.INFO)
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
local hotpotpath = vim.fn.stdpath("data") .. "/lazy/hotpot.nvim"
if not vim.loop.fs_stat(hotpotpath) then
  vim.notify("Bootstrapping hotpot.nvim...", vim.log.levels.INFO)
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/rktjmp/hotpot.nvim.git",
    hotpotpath,
  })
end
vim.opt.runtimepath:prepend({hotpotpath, lazypath})

require("hotpot").setup({
  provide_require_fennel = true
})

-- include hotpot as a plugin so lazy will update it
local plugins = {"rktjmp/hotpot.nvim"}
require("lazy").setup(plugins)
EOF
WORKDIR /root/project
ENTRYPOINT ["bash"]
CMD ["-c", "echo '\n# INTIAL-STATE'; pwd; tree; nvim fnl/stuff/init.fnl +:write +:quit; echo '\n# AFTER-SAVE'; pwd; tree; exec bash"]
```

```bash
# replace `podman` with `docker` if thats what you have installed
podman build --tag hotpot-136 -f Containerfile && podman run --rm -it hotpot-136
```

```
# INTIAL-STATE
/root/project
.
└── fnl
    └── stuff
        ├── init.fnl
        └── macros.fnl

3 directories, 2 files

# AFTER-SAVE
/root/project
.
├── fnl
│   └── stuff
│       ├── init.fnl
│       └── macros.fnl
└── lua
    └── stuff
        └── init.lua

5 directories, 3 files
[root@fd1612b6d320 project]# cat lua/stuff/init.lua
local _1_ = {1, 1}
if ((_G.type(_1_) == "table") and (nil ~= _1_[1]) and (_1_[1] == _1_[2])) then
  local a = _1_[1]
  return true
else
  local _ = _1_
  return false
end
```

**Comment by homedirectory** [comment]
Setting `provide_require_fennel = true` in the global Hotpot config solved the issue.
Thanks, @rktjmp
