### ISSUE TITLE
Installing with luarocks

### ISSUE THREAD

**Issue by horanmustaplot** [rktjmp/hotpot.nvim#138]
Nice plugin BTW :)
Can you add the way to install it with luarocks?

**Comment by rktjmp** [comment]
Do you mean with a package manger (rocks.nvim/lazy.nvim) or luarocks itself?

I can't see much use for installing hotpot via luarocks itself, outside of neovim. You would just `luarocks install hotpot.nvim` but as for hooking it up, you're on your own.

With rocks.nvim, `Rocks install hotpot.nvim` works, but it seems you need to manually call `require("hotpot")` after setting up rocks in your init.lua file. Normally nvim automatically runs hotpots runtime file but it seems `rocks.nvim` doesn't work in this case, I think this is my fault for not specifying the runtime dir in the workflow or whatever.

I can't see how to specifiy a luarock in a lazy.nvim spec on the doc site https://lazy.folke.io/spec so I was unable to test.

**Comment by horanmustaplot** [comment]
> Do you mean with a package manger (rocks.nvim/lazy.nvim) or luarocks itself?
> 
> I can't see much use for installing hotpot via luarocks itself, outside of neovim. You would just `luarocks install hotpot.nvim` but as for hooking it up, you're on your own.
> 
> With rocks.nvim, `Rocks install hotpot.nvim` works, but it seems you need to manually call `require("hotpot")` after setting up rocks in your init.lua file. Normally nvim automatically runs hotpots runtime file but it seems `rocks.nvim` doesn't work in this case.
> 
> I can't see how to specifiy a luarock in a lazy.nvim spec on the doc site [lazy.folke.io/spec](https://lazy.folke.io/spec) so I was unable to test.

Oh thanks I got it:) It seems there's few tuturials on configuring neovim with fennel, I know it's far away from what I've asked... but the language seems to be clearer than lua in doing configs any tuturial in doing so :)

**Comment by rktjmp** [comment]
I added rocks.nvim specific instructions to the readme. Note you must use version `0.13.1` or greater as we needed a work around for some of luarocks behaviour.

I find Fennel much more fun to use than regular lua.

Going to close this as I think its sorted now.
