### ISSUE TITLE
Clonning hotpot with --single-branch breaks Lazy

### ISSUE THREAD

**Issue by sarna** [rktjmp/hotpot.nvim#139]
Hi, first of all thanks a lot for making Hotpot, I've been using it for years with good results :)

I followed the instructions in the README for Lazy.nvim, but when I installed it, it kept complaining about a failed assertion [here](https://github.com/folke/lazy.nvim/blob/077102c5bfc578693f12377846d427f49bc50076/lua/lazy/manage/git.lua#L125). I think Lazy expects the plugin repo to be on some branch. When I ran `git status` in the Hotpot directory, it said:
```console
[sarna@lima-default hotpot.nvim]$ git status
Not currently on any branch.
nothing to commit, working tree clean
```
All the other plugins (except Lazy itself for some reason) seem to have branches:
```console
[sarna@lima-default nvim-lspconfig]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[sarna@lima-default lazy]$ cd ../ale/
[sarna@lima-default ale]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
I removed the `--single-branch` from `init.lua`, removed the Hotpot directory, and restarted Neovim. It started working without Lazy complaining about failed asserts. So I think this argument should be removed from install instructions.

**Comment by rktjmp** [comment]
Ha, I just noticed this tonight too! I have an updated readme on the way :)

**Comment by rktjmp** [comment]
All sorted, thanks for the report!

**Comment by rktjmp** [comment]
I noticed there were some additional quirks with lazy, you must call `vim.loader.enable()` before calling `require("hotpot")`.

Please see the updated install instructions in the readme for more information, including a "structured setup" with a plugin dir.
