### ISSUE TITLE
Take advantage of lua binary loader when PR is merged

### ISSUE THREAD

**Issue by rktjmp** [rktjmp/hotpot.nvim#26]
There is a Neovim PR that saves a loaded lua module via string.dump, meaning later loads can skip the interpreter.

Ideally we would be able to take advantage of this without extra effort, *or* at least clone the code for hotpot.

Depending on the final implementation in Neovim, we either:

- piggy back internal implementation if it is exposed
  - Find or write hotpot cache file (the lua) when needed
  - Call out to `neovim.lua_loader(path)` to load path into cache / load from cache
  - This depends on how nvim's code works, not preferred option unless they intentionally expose the API
- Output hotpot cache files into RTP and then return "not found" for requests which kicks back down the chain to nvims loader
  - instead of writing to `hotpotcache/home/user/..../project/my/module.lua` we write to `hotpotcache/my/module.lua` and add `hotpotcache/` to the RTP.
  - *requires* hotpot to be the first loader/ahead of nvims (probably ok to enforce)
  - Opens  the `./?.lua` part of lua's package.path for collisions. This *mostly* wont impact users AFAIK since plugins can't use that anyway, but it would effect `:Fnl` commands that call require.
    - could check for relative require finds and act differently for those
    - Probably actually an option to hotpot: `cache_style: shallow|deep` which defaults to shallow for most people.
- Clone the implementation internally
  - +most control, +code isn't very big
  - -extra maint, -pref to not double up

See:

Neovim PR (title slightly under described) https://github.com/neovim/neovim/pull/15436
Extracted mpack loading https://github.com/lewis6991/impatient.nvim

**Comment by babygau** [comment]
I tried `impatient.nvim` with both `hotpot` and `aniseed`. While I can see significant startup time when using `aniseed`, `hotpot` is not, it's almost double my startup time when compare with `aniseed` (same config)

```
# packer profile
               colorscheme           sequenced loading
aniseed          5.7                       4.7
hotpot           13.4                      16.2
```

**Comment by rktjmp** [comment]
I assume these are in ms?

Since hotpot doesn't compile into the RTP (it manages its own cache, for better or worse), where as aniseed does (AFAIK), impatient wont pickup hotpot's compiled code.

Because we have an extra step of staleness checks (fnl -> lua), for now I am waiting on whatever mainline behaviour to be settled before proceeding. I do have a local branch with a version of the byte code loader experimentally implemented, but I would prefer to use nvims own if possible.

**Comment by babygau** [comment]
Thank you for your detailed explanation. It's in `ms`.  Definitely no rush to implementation this feature at your end. I just want to give you the bird eyes view 🐦 of how fast the upcoming PR could be 🙂

**Comment by rktjmp** [comment]
#51
