### ISSUE TITLE
`require("fennel")` from `.lua` file breaks `provide_require_fennel` on a macro file

### ISSUE THREAD

**Issue by datwaft** [rktjmp/hotpot.nvim#39]
I finally got to reproduce the bug we were talking about: https://github.com/rktjmp/hotpot.nvim/issues/38#issuecomment-927229883.

It seems that requiring Fennel from the `init.lua` file breaks the `provide_require_fennel` configuration option for the macro files.

## How to reproduce

I created this repository to reproduce the issue using Docker: [datwaft/hotpot-issue_39](https://github.com/datwaft/hotpot-issue_39).

**Comment by datwaft** [comment]
Btw, executing the following snippet using `:Fnl` also reproduces the issue:
```fennel
(macro test []
  (local {: view} (require :fennel))
  (print view))
(test)
```
If you change `macro` to `fn` it's no longer reproduced.

**Comment by rktjmp** [comment]
Seems fixed...

![image](https://user-images.githubusercontent.com/866010/200129411-9d1d22f9-ddf7-4797-b7f8-d403093fb35d.png)
