### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rktjmp** [rktjmp/hotpot.nvim#4]
Sorting out fennel, lua to fennel, how everything fits together and how to run a fennel test suite was a bit much when I just started mucking around with the idea in my dot files.

**Comment by alexaandru** [comment]
I'll just leave this here, maybe it helps :) : I implemented a tiny testing framework for my own plugin, here: https://github.com/alexaandru/nvim-lspupdate/blob/fennel/fnl/test/init.fnl , here are the test cases: https://github.com/alexaandru/nvim-lspupdate/blob/fennel/fnl/test/util.fnl and here how is all being run: https://github.com/alexaandru/nvim-lspupdate/blob/fennel/Makefile#L5 and it all works like a charm: https://github.com/alexaandru/nvim-lspupdate/actions/runs/1101496110 :) 

Thank you for Hotpot, it has ruined my life in the most wonderful way :) All I do now is rewrite everything in Fennel... :D Cheers!

**Comment by rktjmp** [comment]
Thanks :+1: I will have a look through it!
