### ISSUE TITLE
Reloading config with `:Fnlfile` or `:source` always look for macro file on current pwd

### ISSUE THREAD

**Issue by iagoleal** [rktjmp/hotpot.nvim#43]
Hello! First of all I want to thank you for this marvelous plugin, being able to write my config in fennel has been tons of fun.
Unfortunately, I am having a couple troubles trying to figure out how to recompile fennel files on the fly.

So, a simplification of my current `.config/nvim/` is the following folder structure:
```
├── fnl/
│   ├── macros.fnl
│   ├── startup.fnl
├── init.lua
```
where `init.lua` requires `hotpot` and `startup`, and `startup.fnl` uses the macros defined in `macros.lua`.
All is well and good for loading the files on startup.
The problem arises when I make some modification on `startup.fnl` during a session and want to reload it on the fly.
While hotpot scans the `.config/nvim/fnl/` folder for loading modules with require, it seems to only scan the current pwd for the `:Fnlfile` or `:source` commands.
This behaviour is great for loading standalone fennel files but forces me to change my pwd everytime I want to reload the config.  
I've looked through hotpot's docs but couldn't find how to change the macro searching behaviour when using `:source` instead of `require` . Is there any way to do that?

**Comment by rktjmp** [comment]
Can you try the source-cmd branch? 

https://github.com/rktjmp/hotpot.nvim/tree/source-cmd

It will ask you if you want to delete the cache file for now, I will have to patch a "no confirm" argument into that later.

It also makes some assumptions that what you're sourcing is under a "fnl" folder so we can guess the module name for the require call (needed so hotpot knows to do work).

The `:Fnl*` commands sort of operate outside of the main hotpot setup (they dont create cache files and wont patch the macro searcher (perhaps an oversight)) so I was probably over zealous when linking `:source` to `:Fnlfile`.

**Comment by iagoleal** [comment]
Just tested the branch and it seems to be working as expected.
Thank you very much!

**Comment by rktjmp** [comment]
Sorry took me a moment to put this in the main branch.

**Comment by avegancafe** [comment]
I know this is an issue from a long time ago, but for some reason `source $MYVIMRC` when changing `macros.fnl` for example doesn't trigger a recompile, but `source`ing the file directly does. Is that known behavior?

**Comment by rktjmp** [comment]
Does `:messages` show anything?

> but sourceing the file directly does

Do you mean `:source some/fnl/file.fnl` or `:source ~/.config/nvim/init.lua` (manually expanding the $ var)?

What is `$MYVIMRC`s value?

`:source` will "unload" the module by setting `packages.loaded[modname] = nil` but it wont go any deeper than that, and only if it can guess the mod name. So for $MYVIMRC it may not be able to guess the mod name as it looks for something under `fnl/`.

I would bet that the child modules are not getting unloaded, so they are never *reloaded*, so the changes are never picked up.

You may want to write a small function that just nukes anything under a certain module namespace to ensure all your config mods are unloaded:

```fennel
;; may not be functional
;; assumes you have your config under "fnl/my/config/..."
(each [_i mod (ipairs package.loaded)]
  (if (string.match mod "^my.config")
    (tset package.loaded mod nil)))
(vim.cmd.source $MYVIMRC) ;; probably need vim.expand or something here for the var
```
