### ISSUE TITLE
Fennel files under ~/.config/nvim/plugin/* are not loaded automatically

### ISSUE THREAD

**Issue by alexaandru** [rktjmp/hotpot.nvim#44]
Given the following files:

```
$ grep . plugin/*
plugin/bar.vim:echo 'bar.vim'
plugin/baz.lua:print "baz.lua"
plugin/foo.fnl:(print :foo.fnl)
```

loading vim, will automatically load, the `vim`, the `lua` but not the `fnl` file:

```
$ nvim --headless +q
bar.vim
baz.lua
```

It would be very nice if fennel files would also be loaded, similar to lua files. That would give us more flexibility into how we organize our config files.

To a more general note, it would be great if `fennel` would be supported everywhere where `lua` is (like `colors`, `after`, etc.). The https://github.com/neovim/neovim/issues/12670 issue extended where lua can be used (including `plugin` folders).

**Comment by alexaandru** [comment]
Well, after looking at the PR https://github.com/neovim/neovim/pull/14686/files - this is probably impossible to handle in this plugin, as it requires changing how the neovim `runtime` command works, which is the one responsible for the loading from the folders above mentioned...

**Comment by rktjmp** [comment]
Yeah we can only hook lua's `require` path, so any plugin stuff cant be hooked.

Previously I posted this https://github.com/rktjmp/hotpot.nvim/discussions/41 but haven't personally tested it (probably fine though).

Not sure if there may bet an autocmd that could be hooked to act when RTP dirs are scanned, check for *.fnl files and load them.

You could hook VimEnter and manually search the whole rtp plugin/colors/etc folders and load the fennel files but I doubt that in particular would make it into Hotpot core as it's probably pretty expensive and would currently mean loading fennel if it found any files which is slow.

Probably the cache API should have a user function that *creates* a cache file for any given file. Right now you'd have to patch the lua package.path to include the non-standard dir the require normally.

All in all, having a lua "patch loader" is probably simplest.

**Comment by alexaandru** [comment]
Thank you very much for the detailed reply. Yes, the solution from #41 should do and seems the cleanest for now. I've personally used it from `colors` folder (https://github.com/alexaandru/froggy/blob/master/colors/froggy.lua) but it should work from wherever lua files are supported.

Gonna close this one,

Cheers!
