### ISSUE TITLE
Hotpot doesn't properly transpile files with kebab-case names

### ISSUE THREAD

**Issue by datwaft** [rktjmp/hotpot.nvim#53]
This issue is about Hotpot not transpiling properly files with names that are in kebab-case (e.g. `module-in-kebab-case`). You can see in the following image that the file is transpiled to a directory instead of a lua file.

![image](https://user-images.githubusercontent.com/37723586/159521661-519d6c45-9d8e-4fb6-a4d3-b63e7dfbd184.png)

This makes neovim crash with a file not found error.

![image](https://user-images.githubusercontent.com/37723586/159544642-f61a1080-7642-47c3-931a-9e555eaae6f3.png)

## How to reproduce the issue

I created the following repository using Docker: [datwaft/hotpot-kebab-case-issue](https://github.com/datwaft/hotpot-kebab-case-issue)

**Comment by rktjmp** [comment]
Knew you'd find something! :1st_place_medal: 

Fixed in 2d61b8d

**Comment by datwaft** [comment]
Thanks! It works now!
![image](https://user-images.githubusercontent.com/37723586/159595358-f259c3bf-3215-4fe4-8a7e-963dc880ead5.png)
