### ISSUE TITLE
hotpot.nvim breaks Nix/Neovim/home-manager configuration

### ISSUE THREAD

**Issue by harrisonthorne** [rktjmp/hotpot.nvim#54]
Apologies if this is the wrong place to report this, but this seems to be a "regression" of sorts with hotpot.

The error occurs while configuring Neovim with home-manager:

```console
$ nix log /nix/store/sqrmgrw58sycvi99ldsdpwhxm3k5ilpv-neovim-0.6.1.drv
Generating remote plugin manifest
Error detected while processing /nix/store/jlznc3if8w0myi9h3v9xaqlih8zaqgh7-vimplugin-hotpot.nvim/plugin/hotpot.vim:
line    2:
E5108: Error executing lua Vim:E739: Cannot create directory /nix/store/silam09pv3pvvvx4zrpkjvccllfxggpn-vim-pack-dir/pack/home-manager/start/vimplugin-hotpot.nvim/lua/hotpot/api: permission denied
stack traceback:
	[C]: in function 'mkdir'
	.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:65: in function 'compile_dir'
	.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:66: in function 'compile_dir'
	.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:82: in function 'compile_hotpot'
	.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:105: in main chunk
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /nix/store/d1innpx3r0mrs1rxhbfh4sl80cv827bc-neovim-0.6.1/rplugin.vim
Generating rplugin.vim failed!
```

## More info

**hotpot.nvim broken commit hash:** 72704e1914648774a4fb42f57ca411d689e08ae6

**last hotpot.nvim commit that worked:** 0e0e8dff92f47c85bf4893f50bec4e36d6c7d0b9 

**Neovim version:** 0.6.1 (fails with nightly, too)

[hotpot plugin definition in my config](https://codeberg.org/harrisonthorne/dotfiles/src/commit/0851de84de05ed44b6156381a3c54bb5d4489005/flake.nix#L50)

[hotpot plugin usage in my neovim config](https://codeberg.org/harrisonthorne/dotfiles/src/commit/0851de84de05ed44b6156381a3c54bb5d4489005/nvim/mod.nix#L13)

Thanks in advance for your insights :grin:

**Comment by rktjmp** [comment]
Hotpot ships with a bootstrapper that will compile hotpot itself, it basically traverses `hotpot/fnl/*` and writes it to `hotpot/lua/*` (except for `hotpot.fnl` which is the pre-compiled bootstrapper). Looks like that is having trouble with permissions? I wonder if homemanager sets up some restrictive permissions?

`Cannot create directory /nix/store/silam09pv3pvvvx4zrpkjvccllfxggpn-vim-pack-dir/pack/home-manager/start/vimplugin-hotpot.nvim/lua/hotpot/api: permission denied`

The SHA that works is basically just before `0.2.0` which included the re-written bootstrapper.

Per your last nix issue, I wonder if you can run a post-install command to enforce `hotpot/lua` as writable, before you run nvim the first time and the code gets compiled?

[Relevant code](https://github.com/rktjmp/hotpot.nvim/blob/72704e1914648774a4fb42f57ca411d689e08ae6/fnl/hotpot.fnl#L45-L73), patches welcome, perhaps it's naive to assume it inherits a good umask.

**Comment by harrisonthorne** [comment]
So I found [here](https://github.com/NixOS/nixpkgs/blob/932273493dbe9f946ef744004090fb769186fd20/pkgs/applications/editors/neovim/wrapper.nix#L104) is where that error is being thrown. This is where Nix and home-manager "wrap" neovim and build its configuration. But for the life of me, I can't figure out why this "remote plugin manifest generation" script is being included in the first place :P

Anyway--

> The SHA that works is basically just before 0.2.0 which included the re-written bootstrapper.

My guess is that the bootstrapper from before didn't run during/before this `:UpdateRemotePlugins` invocation of `nvim` (and it is now)? It seems to me that this isn't a matter of *how* the bootstrapper runs but rather *when* (or *why*)

**Comment by rktjmp** [comment]
Yeah previously hotpot would compile itself to `~/.cache/nvim/home/<you>/<your-nvim-plugins-dir>/hotpot/` but now it compiles directly into `~/<your-nvim-plugins-dir>/hotpot/lua/`, but nix sets that folder to be read only I guess.

Can you do something like this?

```nix
home.activation = {
  unlockHotpotLua = home-manager.lib.hm.dag.entryAfter ["writeBoundary"] ''
    HOTPOT_DIR="${config.xdg.localHome}/share/nvim/site/pack/hotpot/lua" # no idea where the real dir is
    if [[ -d "$HOTPOT_DIR" ]]; then
      $DRY_RUN_CMD chmod 744 "$HOTPOT_DIR"
    fi
  '';
};
```

**Comment by mixedCase** [comment]
Is there any way to revert to the previous behavior? Nix stores hotpot (and every other package) in a read-only store, not unlike most system-level package managers that store files as root-owned.

If it's possible to configure the folder the bootstrapping takes place in (or having it go back by `$XDG_CACHE_HOME`) we can fix this without breaking the permission model.

**Comment by rktjmp** [comment]
We compile to `lua/` to avoid having the extra search target in `package.path` (and we don't ship a full `lua/` package for my own QOL).

I have added a branch, https://github.com/rktjmp/hotpot.nvim/tree/nix-compat which will check for a global `__hotpot_bootstrap_target_dir` which should be set before hotpot is required. It should be a full path to somewhere you can write to, probably you would want:

```lua
__hotpot_bootstrap_target_dir = vim.fn.stdpath("cache") .. "/some/path"
require("hotpot")
```

If someone wants to test the branch that would be useful. Hotpot has always (will always?) had the "just `require("hotpot")`" minimal setup, so we can't really pass options to the bootstrapper without globals :vomiting_face:.

**Comment by n4074** [comment]
I am affected by the same issue trying to use hotpot with nix. The `nix-compat` branch works for me.

**Comment by rktjmp** [comment]
Thanks for testing, merged.
