### ISSUE TITLE
delete cache

### ISSUE THREAD

**Issue by Suyashtnt** [rktjmp/hotpot.nvim#71]
How can I delete compilation cache? Its currently messing up and anytime I update my config I keep on getting this error (I deleted lua/plugins as now its written in fennel)

![image](https://user-images.githubusercontent.com/45307955/181753253-aa7b442f-5be2-444d-bd9e-d4cef481e619.png)

**Comment by rktjmp** [comment]
```fennel
(let [cache-api (require :hotpot.api.cache)]
  (cache-api.clear-cache))
```

Select that and evaluate it with `:Fnl` or similar.

See also `:h hotpot.api.cache` for other functions and path information.
