### ISSUE TITLE
requireAsInclude

### ISSUE THREAD

**Issue by shaunsingh** [rktjmp/hotpot.nvim#72]
Hi, sorry to bother you but is there a way to pass flags to the fennel compiler through hotpot? I would ideally like to pass the `--require-as-include` flag to fennel

**Comment by rktjmp** [comment]
No bother!

Anything given to setup's `compiler.modules` and `compiler.macros` options is passed as is-to the fennel compiler. See`:h hotpot-setup`. Look out for the pitfalls listed in regards to forgetting to include macro `env` options!

If an option doesn't seem to work, please try to create a test case with regular fennel to ensure it's not an implementation quirk there, we generally don't do much with compilation but pass options along.

(There is also a warning in the docs about passing options to `api.compile` but that's actually out of date as `api.compile` now accepts an options table).

**Comment by shaunsingh** [comment]
Wonderful, passing `requireAsInclude = true` did the trick, thank you!
