### ISSUE TITLE
Add ways to execute fennel code from neovim

### ISSUE THREAD

**Issue by shadmansaleh** [rktjmp/hotpot.nvim#8]
@rktjmp I'm not sure if this falls under this plugin . But since it encourages using fennel even in small amounts I think it should help a bit with writting fennel too :)

It's too hard to write fennel without someway of exexuting and verifying that the code works . hotpot only loades the code once on `require` . Even re requiring the file after clearing package cache is clumsy .

After a good fight with fennel 😂
 I've put this in my configs

```fennel
(fn get_range_lines [line1 line2]
  "
    Get buffer lines from range line1 - line2
    line1 & line2 can either be line number or position line [row, col]
  "
  (var retval [])
  (if (= (type line1) "number")
      (set retval (vim.api.nvim_buf_get_lines 0 (- line1 1) line2 false))
    (= (type line1) "table")
      (let [[line1_row line1_col] line1
            [line2_row line2_col] line2
            buf (vim.api.nvim_buf_get_lines 0 (- line1_row 1) line2_row false)]
          (when (> (length buf) 0)
            (tset buf 1 (string.sub (. buf 1) line1_col + 1))
            (tset buf (length buf) (string.sub (. buf (length buf)) 1 (+ line2_col 1)))
            (set retval buf))))
  retval)

(fn exec_fennel_str [...]
   "Executes input strings as fennel code"
  (let [buf (table.concat [...] " ")
        compiled-str ((. (require "fennel") "compileString") buf)]
    ((loadstring compiled-str))))

(fn exec_fennel_range [line1 line2]
  "Execute range from line1 - line2"
  (let [lines (table.concat (get_range_lines line1 line2) "\n")]
     (exec_fennel_str lines)))

(fn exec_fennel_file [fname]
  "Execute file fname"
  (local fname (vim.fn.expand fname))
  (local file (io.open fname))
  (if file
    (let [buf (file:read "*a")]
      (file:close)
      (exec_fennel_str buf))
    (print "File not found")))

(fn exec_fennel [line1 line2 fname]
  "Executes range line1 - line2 when fname isn't provided.
   When fname is provided executes the file.
   Used by :FennelFile command
  "
  (if (= fname "")
    (exec_fennel_range line1 line2)
    (exec_fennel_file fname)))

(fn fennel_operator_eval []
  "Executes range from mark '[ to mark '] set by 'opfunc'"
  (let [line1 (vim.api.nvim_buf_get_mark 0 "[")
        line2 (vim.api.nvim_buf_get_mark 0 "]")]
     (exec_fennel_range line1 line2))
  (if (. (require "exec_fennel") "opfunc_backup")
    (tset vim.o "operatorfunc" (. (require "exec_fennel") "opfunc_backup"))
    (tset (require "exec_fennel") "opfunc_backup"  "")
  ))

(fn exec_fennel_operator []
  "Sets fennel_operator_eval as 'opfunc' and trigures oppending mode"
  (tset (require "exec_fennel") "opfunc_backup" "")
  (tset vim.o "operatorfunc" "v:lua.require'exec_fennel'.fennel_operator_eval")
  (vim.api.nvim_feedkeys "g@" "n" false))

(fn define_commands []
  "Defines vimL api"
  (vim.cmd "
   command! -range=% -nargs=? -complete=file FennelFile :lua require'exec_fennel'.exec_fennel(<line1>, <line2>, <q-args>)
   command! -nargs=+ Fennel :lua require'exec_fennel'.exec_fennel_str(<q-args>)
   au! my_commands SourceCmd *.fnl :FennelFile <afile>
   nnoremap <Plug>(exec-fennel-operator) :lua require'exec_fennel'.exec_fennel_operator()<cr>
   "))

{ : get_range_lines
  : exec_fennel_range
  : exec_fennel_str
  : exec_fennel
  : define_commands
  : exec_fennel_operator
  "opfunc_backup" ""
  : fennel_operator_eval }
```

It provides
1. `:Fennel` that directly executes fennel from argument. like `:lua`
2. `:FennelFile` that executes a fennel file. like `:source` . Just like source it excepts range so you can execute specific regions of curremt buffer with that . If `:FinnelFile` is executed without argument and range it just executes current buffer . Again just mimics `:source` interface.
3. A normal mode map for an operator `\<Plug>(exec-fennel-operator)` . This can execute fennel code from current buffer that is selected by operator . Like I have it mapped to `\<leader>fe` and I can go to a paran and do `<leader>fe%` or `\<leader>fea(` to execute the block
4. Also sets a auto command so you can `:source` fennel files .

If you like you can put some of these interface in this plugins as helper.

**Comment by rktjmp** [comment]
Thought Lisp had too many parens for you?? :vomiting_face: 

Yeah I have been debating whether a `:Fnl` command was scope creep or not but I had been coming around to it. I think if Hotpot goal is "make you think Fennel is native" it makes sense.

I don't want to fall into the trap of writing a REPL when `olical/conjure` does such a great job, but I think these very focused tools would be a good fit.

Don't worry about submitting a patch as Hotpot will probably get a minor code-shuffle in the next few days now that I understand the problem space better and I'll probably fold them in then if that's ok. Right now they don't really have a place to live.

Adding `:source` support is particularly amazing, had no idea about `SourceCmd`!

**Comment by shadmansaleh** [comment]
> Thought Lisp had too many parens for you?? 

It still is . As I said had a good fight with fennel . I thought I'll give fennel another try with hotpot.

>  if Hotpot goal is "make you think Fennel is native"

I've been treating hotpot that way . Definatly your call whether this makes sense here . `:Fnl` will be a better name . I didn't make a pr as I wasn't sure whether this makes sense here . Also the code might be crap in terms of lisp . I haven't written this much lisp in rest of my life 😁 . Just had written it as helper for my config thought I'd just make a proposal here .

> I don't want to fall into the trap of writing a REPL when olical/conjure does such a great job

I agree . Complete REPL would be too much . 

> Don't worry about submitting a patch

I can put it in a separate file and make it use hotpots embeded compiler instead of system one if that's what you need .

> I'll probably fold them in then if that's ok

I'm not sure what you mean by folding them . But you can make whatever modification you want .

> Adding :source support is particularly amazing, had no idea about SourceCmd!

I didn't either before looking at neovims source :P . Also with `SourceCmd` `:runtime` also works . If ranges were exposed though SourceCmd we wouldn't need a FennelFile at all .

**Comment by rktjmp** [comment]
```clojure
(fn fennel_operator_eval []
  "Executes range from mark '[ to mark '] set by 'opfunc'"
  (let [line1 (vim.api.nvim_buf_get_mark 0 "[")
        line2 (vim.api.nvim_buf_get_mark 0 "]")]
     (exec_fennel_range line1 line2))
  (if (. (require "exec_fennel") "opfunc_backup") ;; backup always == ""
    (tset vim.o "operatorfunc" (. (require "exec_fennel") "opfunc_backup")) ;; always runs?
    (tset (require "exec_fennel") "opfunc_backup"  "")
  ))

(fn exec_fennel_operator []
  "Sets fennel_operator_eval as 'opfunc' and trigures oppending mode"
  (tset (require "exec_fennel") "opfunc_backup" "") ;; always sets backup to ""
  (tset vim.o "operatorfunc" "v:lua.require'exec_fennel'.fennel_operator_eval")
  (vim.api.nvim_feedkeys "g@" "n" false))
```

@shadmansaleh  Feel like I am missing something with the `opfunc_backup` stuff? Seems like it's effectively a no-op? Is it missing code?

The docs don't seem to imply you have to save state of the last opfunc, is it just some left over test code?

**Comment by shadmansaleh** [comment]
You're right . It's a bug. I think my code was causing error somwhere and kept changing different stuff but when udoing those changes I missed this.
```diff
diff --git a/fnl/hotpot/exec_fennel.fnl b/fnl/hotpot/exec_fennel.fnl
index d687c03..a38e319 100644
--- a/fnl/hotpot/exec_fennel.fnl
+++ b/fnl/hotpot/exec_fennel.fnl
@@ -65,7 +65,7 @@
 
 (fn exec_fennel_operator []
   "Sets fennel_operator_eval as 'opfunc' and trigures oppending mode"
-  (tset (require "hotpot.exec_fennel") "opfunc_backup" "")
+  (tset (require "hotpot.exec_fennel") "opfunc_backup" vim.go.operatorfunc)
   (tset vim.o "operatorfunc" "v:lua.require'hotpot.exec_fennel'.fennel_operator_eval")
   (vim.api.nvim_feedkeys "g@" "n" false))
 
```
Now looking at it a ton of strings ("") I used could be replaced by `:`. Should I make another pr ?

Docs doesn't imply but I didn't want to leave user on changed state that's why backup & restore.

**Comment by rktjmp** [comment]
How am I supposed to *use* the operator? I have it mapped, it's feeding g@ but I cant get it to actually fire on any code.

Tried `i"` `a)` `$` etc. Should be working right?

**Comment by rktjmp** [comment]
Nevermind, seems https://github.com/neovim/neovim/issues/14157 is the cause, can't use `
"v:lua.require('hotpot.user.eval').eval_operator"`.
