### ISSUE TITLE
unknown identifier in strict mode: vim

### ISSUE THREAD

**Issue by monkoose** [rktjmp/hotpot.nvim#82]
Trying to convert from `aniseed` to `hotpot`. And got a lot of such errors, which are happens inside `(macro ...)` blocks.

I definitely doing something wrong, but with aniseed it have worked. An now with `hotpot` i can't use any globals inside macros. My macro definitition just split throw config, not in some specific file. Currently my `conf/maps.fnl` is cause of the errors.
Have spend a lot of time to fix this issue without any success.

You can find my config for hotpot branch (it's currently a mess) here https://github.com/monkoose/neovim-fennel/tree/hotpot
Starting point is `init.lua` and then `conf/init_fnl.fnl`
Not an lisp/fennel expert so my macros are ugly too (wanted to make them do too much, will simplify them after fix to this issue).

Only have found `allowedGlobals = false` compiler option as a workaround for strict mode (but it doesn't help for me).
Any help? Should i split macros into different file? Where to put it and how to name it?

**Additional info**
OS: ArchLinux
neovim version: 0.7.2 from oficial archlinux 'community' repository

**init.lua**
```lua
require("hotpot").setup()
require("fnl_init")
```
**fnl/fnl_init.fnl**
```fennel
(import-macros {: strict} :macros)

(local pack (require "packer"))

(fn load-plugins [use]
  (use "wbthomason/packer.nvim")
  (use "rktjmp/hotpot.nvim"))

(pack.startup load-plugins)

(strict)
```
**fnl/macros.fnl**
```fennel
(fn strict [arg]
  (vim.pretty_print "test"))

{: strict}
```

This minimal neovim config gives such error to me
```
Error detected while processing /home/monkoose/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/monkoose/.config/nvim/init.lua:2: module 'fnl_init' not found:Compile error in /home/monkoose/.config/nvim/
fnl/fnl_init.fnl:1:0
  Compile error in /home/monkoose/.config/nvim/fnl/macros.fnl:2:3
  unknown identifier in strict mode: vim

  (^[[7mvim.pretty_print^[[0m "test"))
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim if you really want a global.
* Try moving this code to somewhere that vim is in scope.
* Try binding vim as a local in the scope of this code.

^[[7m(import-macros {: strict} :macros)^[[0m
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim

  (^[[7mvim.pretty_print^[[0m "test"))
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim if you really want a global.
* Try moving this code to somewhere that vim is in scope.
* Try binding vim as a local in the scope of this code. if you really want a global.
* Try moving this code to somewhere that vim

  (^[[7mvim.pretty_print^[[0m "test"))
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim if you really want a global.
* Try moving this code to somewhere that vim is in scope.
* Try binding vim as a local in the scope of this code. is in scope.
* Try binding vim
  (^[[7mvim.pretty_print^[[0m "test"))
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim if you really want a global.
* Try moving this code to somewhere that vim is in scope.
* Try binding vim as a local in the scope of this code. as a local in the scope of this code.
        no field package.preload['fnl_init']
        no file '/usr/share/lua/5.4/fnl_init.lua'
        no file '/usr/share/lua/5.4/fnl_init/init.lua'
        no file '/usr/lib/lua/5.4/fnl_init.lua'
        no file '/usr/lib/lua/5.4/fnl_init/init.lua'
        no file './fnl_init.lua'
        no file './fnl_init/init.lua'
        no file '/home/monkoose/.luarocks/share/lua/5.4/fnl_init.lua'
        no file '/home/monkoose/.luarocks/share/lua/5.4/fnl_init/init.lua'
        no file './fnl_init.lua'
        no file '/usr/share/luajit-2.1.0-beta3/fnl_init.lua'
        no file '/usr/local/share/lua/5.1/fnl_init.lua'
        no file '/usr/local/share/lua/5.1/fnl_init/init.lua'
        no file '/usr/share/lua/5.1/fnl_init.lua'
        no file '/usr/share/lua/5.1/fnl_init/init.lua'
        no file '/usr/lib/lua/5.4/fnl_init.so'
        no file '/usr/lib/lua/5.4/loadall.so'
        no file './fnl_init.so'
        no file '/home/monkoose/.luarocks/lib/lua/5.4/fnl_init.so'
        no file './fnl_init.so'
        no file '/usr/local/lib/lua/5.1/fnl_init.so'
        no file '/usr/lib/lua/5.1/fnl_init.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/monkoose/.config/nvim/init.lua:2: in main chunk
```

**Comment by monkoose** [comment]
@babygau didn't help. Updated repository you can check how i did it.

> Off topic but your map! macro makes me miss my old doom-emacs :)

Will change them (too complex especially for me who are not expert)

**Comment by monkoose** [comment]
I have imported `map!`. set-map! is helper macro for `map!` should i import it too?

It's the same error

```
Error detected while processing /home/monkoose/.config/nvim/init.lua:
E5113: Error while calling lua chunk: module 'conf.maps' not found:Compile error in /home/monkoose/.config/nvim/fnl/conf/maps.fnl:1:0
  Compile error in /home/monkoose/.config/nvim/fnl/conf/macros.fnl:2:15
  unknown identifier in strict mode: vim

  (local opts (^[[7mvim.tbl_extend^[[0m "force" {} (or opts {})))
* Try looking to see if there's a typo.
* Try using the _G table instead, eg. _G.vim if you really want a global.
* Try moving this code to somewhere that vim is in scope.
* Try binding vim as a local in the scope of this code.
```

**Comment by monkoose** [comment]
> Highly recommend this for your reference, easier to grok and make your own
> https://github.com/datwaft/themis.nvim

Yes i saw it. I took inspiration from his config when i switched to hotpot.

I don't get it either. I don't see anything specific that he done (he just import macros from this plugin). And this plugin is just collection of macros not even with some specifc filename as `macros.fnl`. :(

**Comment by monkoose** [comment]
`_G.vim` is a help (but then i need to rename every global like so in macros`. I prefer to find what is causing such issue.

For some reason config dir doesn't have any lua folder in my config. Cleared `.cache/nvim/hotpot` but issue is still present.

**Comment by monkoose** [comment]
> Possibly, you put `lua` in gitignore :D

I'm definitely stupid, but not so much :) Have checked hidden files too.

**Comment by monkoose** [comment]
> Sorry that I can't help much. Actually I had that issue long time ago, especially when trying `fennel-cljlib`. But it should not be your issue now. You could pull datwaft repo and test if the prob still persists (well, with your system :|).

Ok will do it now. Anyway have no idea why `lua/` dir is missing. But it is still like half working my config i still get completions from `cmp` and mappings from it config works too. Weird.

**Comment by monkoose** [comment]
I got some errors from his config here and there (especially some CursorHold events), but it is working and at least it is not a fennel compiler issues. So there are no `unknown identifier in strict mode` problems :(

**Comment by monkoose** [comment]
> So at least we know it's not your system issue, sth strange in your config btw ^ ^ Do you see Lua folder? I'm curious :D

Yes have found it, lua files are actually are in `.cache/nvim/hotpot` directory. Which i previously deleted without any fix to the issue.

**Comment by monkoose** [comment]
Have updated issue message.
With that minimal neovim config i still have error.

**Comment by rktjmp** [comment]
Guessing:

You need to set `:compilerEnv _G` to stop global checking in the macro compiler.

https://fennel-lang.org/api

> compilerEnv: an environment table in which to run compiler-scoped code for macro definitions and eval-compiler calls. Internal Fennel functions such as list, sym, etc. will be exposed in addition to this table. Defaults to a table containing limited known-safe globals. Pass _G to disable sandboxing.

```fennel
  (setup {:provide_require_fennel true
          :compiler {:modules {:correlate true}
                     :macros {:env :_COMPILER
                              :compilerEnv _G
                              :allowedGlobals false}}})
```

https://github.com/rktjmp/hotpot.nvim/issues/22#issuecomment-916148788

**Comment by monkoose** [comment]
Let me try with minimal config, but i have tried this setting before with no result. I literally tried like almost every line from your cookbook.

**Comment by rktjmp** [comment]
https://github.com/rktjmp/hotpot-issue-82

Note that "test" is only output at compile time, so when you first run nvim in the container, or if you edit the file and relaunch.

**Comment by rktjmp** [comment]
```
  env = "_Compiler",
```

Must be `_COMPILER`

**Comment by monkoose** [comment]
kkk

> ```fnl
> (fn strict [arg]
>   `(vim.pretty_print "test"))
> 
> {: strict}
> ```

Holy mother fu..... sh ...... 

So my custom made `(assert (= vim.tbl.....)` where the issue? Why they have worked in aniseed then?

**Comment by monkoose** [comment]
> ```
>   env = "_Compiler",
> ```
> 
> Must be `_COMPILER`

Ok this works. Thank you. I do remember i tried uppercase with mine config.

**Comment by rktjmp** [comment]
Unsure what your intention is, that function is different to what you have in your first post:

```fennel
;; inject the code (vim.pretty_print "test") into the call site
(fn strict [arg]
  `(vim.pretty_print "test"))n

;; run the call (vim.pretty_print "test) _at compile time_
(fn strict2 [arg]
  (vim.pretty_print "test"))
```

**Comment by monkoose** [comment]
> Fennel doesn't know `vim.pretty_print` at compile time.

Seems with the setting from @rktjmp it still works fine. But if i add backquote and remove config it works too.

**Comment by monkoose** [comment]
> Unsure what your intention is, that function is different to what you have in your first post:

Yes. Thank you. I do get it now.

**Comment by monkoose** [comment]
@rktjmp @babygau Thank you both for the help.
Test with minimal config was the thing. Should have done it much earlier.

**Comment by rktjmp** [comment]
See the link I posted to the Fennel API doc, by default only a few functions are available at compile time (so when building macros). By setting `compilerEnv` to `_G`, all functions (well anything in the global scope) are available to be called _at compile time_. This is a sort-of safety feature of Fennel upstream. 

You should be able to look at Aniseeds compiler settings to see what they use, Hotpot should be 100% compatible as long as they have not patched fennel somehow.

Glad you sorted it out, thanks @babygau for lending a hand.

**Comment by monkoose** [comment]
Now my config works even with my weird macros. :smile:

**Comment by monkoose** [comment]
@rktjmp one more question while you are here.
I want to build some addition dir with AOT. Have this code (but it again error with undefined in strict ....)
```lua
  require("hotpot.api.make").build(
    config_dir,
    {
      verbosity = 0,
      compiler = {
        macros = {
          env = "_COMPILER",
          compilerEnv = _G,
          allowedGlobals = false,
        },
      },
    },
    config_dir .. "/colors/half.fnl",
    function(path)
      return path
    end
  )
```

Do i miss something?

**Comment by rktjmp** [comment]
Hmm, it looks OK. The make stuff is a bit weird with how we have to juggle API options, possibly it's not getting passed down. Can you post it to another issue and I will try to look at it tonight.

**Comment by monkoose** [comment]
> Hmm, it looks OK. The make stuff is a bit weird with how we have to juggle API options, possibly it's not getting passed down. Can you post it to another issue and I will try to look at it tonight.

let me try few more things before that. Maybe I will find the solution.

**Comment by monkoose** [comment]
Fixed it. 
My `color/colorscheme.fnl` one again had `(macro ...` form. Seems like even with such addition options macros must be in a different file. And seems like aniseed have no problems with that.
