### ISSUE TITLE
`:h hotpot-cache` no longer works

### ISSUE THREAD

**Issue by datwaft** [rktjmp/hotpot.nvim#91]
This comes from the README:

> This allows the user to easily view the result of the compilation for debugging. See :h hotpot-cache.

I just tried to use `:h hotpot-cache` but the following error appears: `E149: Sorry, no help for hotpot-cache`.

**Comment by rktjmp** [comment]
The docs are auto generated now so it's under `hotpot.api.cache`, thanks for the heads up.
